<?php
return array (
  'button.attach' => 'Đính kèm tập tin',
  'button.cancel' => 'Hủy',
  'button.confirm' => 'Xác nhận',
  'button.copy' => 'Copy',
  'button.delete' => 'Xóa',
  'button.edit' => 'Sửa',
  'button.export' => 'Export',
  'button.hide' => 'Ẩn',
  'button.import' => 'Import',
  'button.login' => 'Đăng nhập',
  'button.merge' => 'Merge',
  'button.move' => 'Move',
  'button.preview' => 'Xem trước',
  'button.purchase' => 'Mua',
  'button.save' => 'Lưu',
  'button.search' => 'Tìm',
  'button.show' => 'Hiện',
  'button.sort' => 'Sort',
  'button.submit' => 'Submit',
  'button.translate' => 'Translate',
);