<?php
return array (
  'nav._default' => 'Default (no selected tab)',
  'nav.contributedThreads' => 'Chủ đề có bài của bạn',
  'nav.currentVisitors' => 'Người đang truy cập',
  'nav.defaultLatestActivity' => 'Hoạt động gần đây',
  'nav.defaultLogOut' => 'Đăng xuất',
  'nav.defaultNewsFeed' => 'Dòng thời gian của bạn',
  'nav.defaultRegister' => 'Đăng ký',
  'nav.defaultYourAccount' => 'Tài khoản của bạn',
  'nav.defaultYourProfile' => 'Hồ sơ của bạn',
  'nav.findThreads' => 'Tìm chủ đề',
  'nav.forumList' => 'Forum list',
  'nav.forums' => 'Diễn đàn',
  'nav.home' => 'Home',
  'nav.latestActivity' => 'Hoạt động gần đây',
  'nav.markForumsRead' => 'Đánh dấu đã đọc',
  'nav.members' => 'Thành viên',
  'nav.newPosts' => 'Bài mới',
  'nav.newProfilePosts' => 'Bài viết mới trong hồ sơ',
  'nav.registeredMembers' => 'Thành viên đã đăng ký',
  'nav.searchForums' => 'Tìm trong diễn đàn',
  'nav.searchProfilePosts' => 'Tìm trong bài viết hồ sơ',
  'nav.unansweredThreads' => 'Chủ đề chưa trả lời',
  'nav.watched' => 'Đã theo dõi',
  'nav.watchedForums' => 'Diễn đàn được theo dõi',
  'nav.watchedThreads' => 'Chủ đề được theo dõi',
  'nav.whatsNew' => 'Có gì mới',
  'nav.whatsNewNewsFeed' => 'Dòng thời gian của bạn',
  'nav.whatsNewPosts' => 'Bài mới',
  'nav.whatsNewProfilePosts' => 'Bài viết mới trong hồ sơ',
  'nav.yourThreads' => 'Chủ đề của bạn',
);